### ISSUE TITLE
sbt assembly results in 'invalid or corrupt jarfile'

### ISSUE THREAD

**Issue by nicl** [sbt/sbt-assembly#109]
I updated a library and now assembly creates a jarfile which is 'invalid or corrupt' (this is the error given by trying `java -jar my.jar`).

Running `unzip -T my.jar` gives:

```
error:  expected central file header signature not found (file #65756).
(please check that you have transferred or created the zipfile in the
appropriate BINARY mode and that you have compiled UnZip properly)
```

Are there any ways to debug these kinds of issues? Could it be due to a library conflict (although I don't get errors relating to this - only some warning about merges which I got before)? Or perhaps I need to clear out my cache or something?

Any tips appreciated,

Nic

**Comment by rmleon** [comment]
It happened to me when I built using 1.7.0_72 and tried running the Jar in 1.7.0_75.
Iwu's workaround worked: building the Jar in Java 1.6 fixed the problem.

**Comment by nicl** [comment]
Just realised I never said thanks for the advice here :( So thanks @lwu and @eed3si9n .

**Comment by onilton** [comment]
For the ones that still fall here, I will post my experience to maybe help anyone facing this issue.

In my case, after a lot of investigation I discovered that sbt assembly was generating a fat jar with a lot of files, and because of an issue with 64 bits (Zip64) `java -jar` thinks the file is corrupted.

This issue is described in http://bugs.java.com/bugdatabase/view_bug.do?bug_id=7194005.

It was fixed in openjdk 8, but the fix was never backported to openjdk 7, so all openjdk 7 versions will present this problem.

If you can't upgrade to openjdk8, there is an workaround: 

Instead of running:
```
java -jar yourgenererated.jar
```
you can run:
```
java -cp yourgenererated.jar Main
```

If you want to make sure this is really your problem, you can run the procedure described in this gist, to generate a really big jar and get the error:

https://gist.github.com/mchv/9645676
