### ISSUE TITLE
publish skips unmanagedResourceDirectories 

### ISSUE THREAD

**Issue by mrt181** [sbt/sbt-assembly#420]
Hi, I am trying to publish an app packaged as an assembly to a private artifact store. I am adding some files to the assembly 

`Compile / unmanagedResourceDirectories += target.value / "protobuf_external_src"`.

That works when I create the assembly with the assembly task but not when I just run publish. In that case those files are absent?
I am using theses settings from the sbt-assembly readme.md

```
  artifact in (Compile, assembly) := {
      val art = (artifact in (Compile, assembly)).value
      art.withClassifier(Some("assembly"))
    }
  addArtifact(artifact in (Compile, assembly), assembly)
```

**Comment by eed3si9n** [comment]
The setting doesn't sound right. What you're doing is including `target / protobuf_external_src` as resource directory as it reads. But if you think about it, it would just grab whatever files that _happens_ to be in the directory at the time because it's *unmanaged*. Normally we use unmanaged directory for `src/main/something` that we already have the actual files. This means that if you run `clean` and run `assembly` you'd likely be able to reproduce your publishing problem.

See https://www.scala-sbt.org/1.x/docs/Howto-Generating-Files.html for generating files.
